version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "joaofranciscosantos"
    default_labels:
      - "dependencies"
