name: CI
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        shell: bash
        run: |
          npm ci
          npm test
